### ISSUE TITLE
Главная страница

### ISSUE THREAD

**Issue by ixax** [ixax/fl-buket#1]
http://ixax.github.io/fl-buket/index.html

**Comment by drdim** [comment]
Нет микроразметки для видео, карточки товара, нет микроразметки для хлебных крошек, отзывы, и огранизации. Нет меты для соц сетей - property og:type... opengraph. vk.com

**Comment by drdim** [comment]
На это странице еще в отзывах, не отрисованы звезды,

**Comment by ixax** [comment]
Да, я хотел механику простановки рейтинг немного попозже сделать. Она есть, надо прикрутить.

**Comment by ixax** [comment]
Рейтинг уехал в fc4f9dd06d7d489c48c2a1dd925aa6abb5a1b4bf

**Comment by ixax** [comment]
Микроформаты унес в https://github.com/ixax/fl-buket/issues/14

**Comment by ixax** [comment]
Тут всё, доп. фичи по карте вынесены в https://github.com/ixax/fl-buket/issues/13
