### ISSUE TITLE
[Футер] Ссылку на адрес сделать кликабельной

### ISSUE THREAD

**Issue by drdim** [ixax/fl-buket#104]
Варианты:
1. Гугл ссылка как проехать https://goo.gl/YoPrWj Как пример.
2. Сделать ссылку на страницу контактов.

**Comment by ixax** [comment]
А откуда проехать?
Телефон ладно, можем узнать положение пользователя и то не факт. А десктоп — скорее всего нет.

**Comment by ixax** [comment]
Выложил. Сделал ссылкой на точку на карте с открытым диалогом маршрута. Пользователю осталось написать лишь свой адрес
