### ISSUE TITLE
[Карточка товара] Мобильная версия

### ISSUE THREAD

**Issue by drdim** [ixax/fl-buket#114]
Както все поехало. Отступы выравнивание размер видео https://drive.google.com/file/d/0B8O4jn0E_cvKeTFNTHNtX1VURmc/view?usp=docslist_api
https://drive.google.com/file/d/0B8O4jn0E_cvKeWtsMUMyRHJpQTA/view?usp=docslist_api

**Comment by drdim** [comment]
content://media/external/file/19435

**Comment by drdim** [comment]
https://drive.google.com/file/d/0B8O4jn0E_cvKeWtsMUMyRHJpQTA/view?usp=docslist_api

**Comment by ixax** [comment]
+ Прошелся по всем отступам и расположениям элементов в десктопе, планшетах и телефонах, все подбил под сетку
+ Поправил https://github.com/ixax/fl-buket/issues/127
+ В мобилках поднял под картинку не только кнопку «Купить», но и все блоки «Купить», «Способы оплаты» и «Доставка». Думаю конверсия будет выше

**Comment by ixax** [comment]
Выложил
