### ISSUE TITLE
Авторизация. Мобилка.

### ISSUE THREAD

**Issue by drdim** [ixax/fl-buket#116]
- [x] Закрывать окно по тапу на окно сообщения.
- [x] Увеличит крестик. Или его функционально вообще на мобилках убрать.
- [x] Обыграть автозакрытием или тапом по нему. 

https://drive.google.com/file/d/0B8O4jn0E_cvKNnhQMmZEWXVaanc/view?usp=docslist_api

**Comment by ixax** [comment]
Не понял…

**Comment by drdim** [comment]
При отправке формы показывается сообщение статус внизу формы. На тачах
крестик заменить на тап по этому сообщению в мобилко и падах.
19 июля 2015 г. 0:46 пользователь "Viacheslav Glushko" <
notifications@github.com> написал:

**Comment by ixax** [comment]
Выложил
