### ISSUE TITLE
Фильтр. Мобилко

### ISSUE THREAD

**Issue by drdim** [ixax/fl-buket#117]
- [x] Выровнять `сбросить фильтр`
- [ ] [У кнопок нет крестика для отмены в верхнем правом углу](https://drive.google.com/file/d/0B8O4jn0E_cvKQkh4YWh6ZlU0dTA/view?usp=docslist_api)
- [x] Еще не работает анчек у кнопок фильтра. Обратно отменить выбор не получается.

**Comment by drdim** [comment]
Еще не работает анчек у кнонок фильтра. Обратно отменить выбор не получается.

**Comment by ixax** [comment]
Анчек - баг, поправлю.
По поводу крестиков спрашивал в https://github.com/ixax/fl-buket/issues/88#issuecomment-122369583

**Comment by ixax** [comment]
Поправил баг с анчеком

**Comment by ixax** [comment]
По багам все, крестик делается в https://github.com/ixax/fl-buket/issues/88#issuecomment-122369583
