### ISSUE TITLE
Каталог. Мобилко.

### ISSUE THREAD

**Issue by drdim** [ixax/fl-buket#118]
Мылит фото. Как от этого избавиться? Оно бо льше чем исходник?

**Comment by ixax** [comment]
Мылит потому что картинки небольшие использованы. Давай попробую вставить с megaflowers. Может быть что получится

**Comment by ixax** [comment]
Мылит потому что картинки были вырезаны из Photoshop-макета x2@ и уменьшены в два раза под dpi-размер :)
Заменил картинки на главной, каталоге, событиях, монобукетах, карточке товара и два больших товара в корзине

**Comment by drdim** [comment]
Даш рекомендации по картинкам для устройств с высоким дипиай? Какие нужны
размеры фоток для каталога в мобилках и у кого ретины дисплеи. Учесть чтобы
лишнего по обьему не передавалось.
19 июля 2015 г. 4:20 пользователь "Viacheslav Glushko" <
notifications@github.com> написал:
