### ISSUE TITLE
Главная. Семь причин. Мобилко.

### ISSUE THREAD

**Issue by drdim** [ixax/fl-buket#119]
Сделать текст и вообще этот блок более нагляляднее. Как то криво этот блок выглядит. Можно немного увнличить шрифт.
https://drive.google.com/file/d/0B8O4jn0E_cvKZ3JQT05FTU1HRWc/view?usp=docslist_api

**Comment by ixax** [comment]
Увеличил шрифт, сделал подложку из цветочной цифры 7 с прозрачностью в 75%, поменял бекграунд на светло-серый. Вообщем выделил как мог :)
