### ISSUE TITLE
[Главная] Кнопка позвонить не по центру в андроиде.

### ISSUE THREAD

**Issue by drdim** [ixax/fl-buket#12]
https://drive.google.com/file/d/0B8O4jn0E_cvKOEV2X3M1YjlTbzg/edit?usp=docslist_api

**Comment by ixax** [comment]
Готово

**Comment by drdim** [comment]
https://drive.google.com/file/d/0B8O4jn0E_cvKUzdaRzM0cXhrbVk/edit?usp=docslist_api
Закругления справа у инпута есть. У кнопки нет. Сделай одинаково. Если у кнопки слева убрали закругления, у инпата справа надо тоже убрать.

**Comment by ixax** [comment]
Готово
