### ISSUE TITLE
Главная. Мобилко. Заказать звонок.

### ISSUE THREAD

**Issue by drdim** [ixax/fl-buket#121]
- [ ] Валидировать телефон.
- [ ] Выдавать о некорректном номере текст. Об ошибке.
- [ ] Выдавать об успешной отправке номера.

**Comment by drdim** [comment]
https://drive.google.com/file/d/0B8O4jn0E_cvKbGdWZjBPZkhyTjA/view?usp=docslist_api

**Comment by ixax** [comment]
Давай не валидировать телефон, а поддерживать маску?
Некорректные сообщения делаются в https://github.com/ixax/fl-buket/issues/99

**Comment by drdim** [comment]
Ок. Но статус когда форма прислала результат от сервера надо сделать.
19 июля 2015 г. 0:41 пользователь "Viacheslav Glushko" <
notifications@github.com> написал:

**Comment by ixax** [comment]
В макетах есть только один вид ошибок: на текстовой странице внизу есть инпут с красным текстом под ним. Значит делаю как там.

**Comment by ixax** [comment]
Выложил
