### ISSUE TITLE
Футер. Ссылка на карту.

### ISSUE THREAD

**Issue by drdim** [ixax/fl-buket#123]
Ссылка у яндекса позволяет сразу построить маршрут от текущего местоположения до адреса назначения как гуглы делают? Сейчас у Меня так сейчас. https://drive.google.com/file/d/0B8O4jn0E_cvKcldGVUktRHpUeTQ/view?usp=docslist_api

**Comment by ixax** [comment]
Не загрузились слои. Перепроверю, ок

**Comment by ixax** [comment]
Это у тебя какие-то проблемы с сетью.
https://yadi.sk/i/ITyWJUzPhwmQU

**Comment by drdim** [comment]
Да там просто не проставляется откуда ехать. После клика на ссылке. Нажимаю
построить маршрут и такая фигня. Там видать нужно както проставлять сразу
текущее местоположение в поле откуда. Чтобы корректно простроился маршрут.
Получилось построить маршрут в 3 клика вместо одного - тыкнуть иконеу
текущего местоположения, а потом жмакнуть мостроить маршрут, а потом
следовать маршруту. На мобилка хочу чтобы сразу прокладывался маршрут к
магазину от текущего местоположения. Может это передавать внешним
приложениям? На айос девайсов есть ссылка которая открывает апл ком потом
редиректит на системную карту или навигацию по умолчанию.
19 июля 2015 г. 5:02 пользователь "Viacheslav Glushko" <
notifications@github.com> написал:
