### ISSUE TITLE
Все страницы. Проект. Оптимизация под мобилки.

### ISSUE THREAD

**Issue by drdim** [ixax/fl-buket#125]
- [x] Запретить масштабирование на мобилках.
- [x] Разместить иконки приложения — заглушки для 3 платформ: винда, айос и различные андроид. Можно взять готовую болванку из мобильного бойлерплейта.

**Comment by ixax** [comment]
+ Убрал изменение масштаба в тачах
+ Перенес startup-splash'и с бойлерплейта
+ Перенес favicon'ы. Но думается мне что неактуальная инфа по фейвиконам. Тут размеры актуальнее: http://habrahabr.ru/post/260777/

Перерисовывать сплеш-скрины и фейвиконы не буду, это задача дизайнера. ТАм более сделать .icon-файл для всех нужных размеров.

**Comment by ixax** [comment]
Выложил https://github.com/ixax/fl-buket/pull/132

**Comment by drdim** [comment]
Булерплейт привел для примера. Да надо актуальные размерчики.
19 июля 2015 г. 4:02 пользователь "Viacheslav Glushko" <
notifications@github.com> написал:
