### ISSUE TITLE
Корзина. удаление товара

### ISSUE THREAD

**Issue by drdim** [ixax/fl-buket#139]
Наезжает верстка при удалении товара из корзины.
http://www.awesomescreenshot.com/image/418760/f9b93580018807e0f9808f4d2ba67e25

**Comment by ixax** [comment]
В мобилках уменьшаем удаленный товар таким образом, чтобы была видна кнопка «Вернуть» и отступы по 20 пикселей сверху/снизу

**Comment by ixax** [comment]
Выложил
