### ISSUE TITLE
Баги. IE11. Файрфокс.

### ISSUE THREAD

**Issue by drdim** [ixax/fl-buket#155]
Бегло пробежался по разным последним версиям браузеров. Надо еще глянуть в ИЕ9
- [x] Едет правая колонка. https://drive.google.com/file/d/0B8O4jn0E_cvKejdtOU01WWU1dXc/view?usp=sharing в ФФ и IE11
- [x] Не работает прокрутка смещается изображение, и просто листает, эффекта 360 нет (возможно из-за первой баги) ФФ IE11 https://drive.google.com/file/d/0B8O4jn0E_cvKUWZyYmFZbDAzbHc/view?usp=sharing
 - [x] Едет верстка состава https://drive.google.com/file/d/0B8O4jn0E_cvKSlpXOFlCNEhyNFU/view?usp=sharing IE11, android
 - [x] Едет верстка состава в ФФ https://drive.google.com/file/d/0B8O4jn0E_cvKdUs5aWZsS0Z3a1E/view?usp=sharing
- [x] Разноцветный в фильтре криво в ФФ и IE11
https://drive.google.com/file/d/0B8O4jn0E_cvKQ213TFJDa001VU0/view?usp=sharing
- [x] Значок вебкамеры в ie11 не по центру в поле ввода не по центру номер телефона. https://drive.google.com/file/d/0B8O4jn0E_cvKMEM5b21FQmxYV1U/view?usp=sharing
- [x] Сафари 7 карточка кнопка звонка не по центру. https://drive.google.com/file/d/0B8O4jn0E_cvKSU9jbk0ydk5zdkU/view?usp=sharing
- [x] './i/rating/empty.png' Не изменена на svg
- [x]  в карточке 360 , после прогрузки, текст накладывается на фото, при вращении выделяется текст.

**Comment by ixax** [comment]
> Значок вебкамеры в ie11 не по центру в поле ввода не по центру номер телефона.

Что не так с телефоном?

**Comment by drdim** [comment]
Что не так с телефоном?
Задран наверх

**Comment by ixax** [comment]
> Сафари 7 карточка кнопка звонка не по центру.

Она расположена так же, как и во всех остальных браузерах…

**Comment by ixax** [comment]
Выложил

**Comment by drdim** [comment]
Не все сделано, в ие с составом те же проблемы, текст 360 налазит на фото, в корзине фотка смещает справа формы оформления заказа, вебкамера значек как прежде

**Comment by drdim** [comment]
Еще лишний пиксель справа в карточке товара появился в ИЕ.

**Comment by ixax** [comment]
> Еще лишний пиксель справа в карточке товара появился в ИЕ.

Скриншот?

**Comment by drdim** [comment]
Вот как в ие корзина
https://drive.google.com/file/d/0B8O4jn0E_cvKVXZuWDYwWGdZVm8/view?usp=sharing
карта
https://drive.google.com/file/d/0B8O4jn0E_cvKSEdoSi1OeVJNMjQ/view?usp=sharing

**Comment by ixax** [comment]
IE11 можно проверять

**Comment by ixax** [comment]
Всё выложил.
