### ISSUE TITLE
Карточка товара

### ISSUE THREAD

**Issue by ixax** [ixax/fl-buket#16]
http://ixax.github.io/fl-buket/product.html
Или нажать на любой товар

**Comment by ixax** [comment]
Основной функционал сделан. Остальное багами с префиксом `[Карточка товара]`

**Comment by drdim** [comment]
С главной не от открываетсЯ карточка.

**Comment by ixax** [comment]
Уже открывается

**Comment by ixax** [comment]
Переоткрываю чтобы сделать попап отдельной страницей. Сейчас попап присутствует на каждой странице, что неудобно при проверке микроразметки.
