### ISSUE TITLE
Корзина ИE11

### ISSUE THREAD

**Issue by drdim** [ixax/fl-buket#162]
- [x] Иe11, ФФ корзина https://drive.google.com/file/d/0B8O4jn0E_cvKLUx2WDFIWV9yZXc/view?usp=sharing
- [x] Ие11 главная https://drive.google.com/file/d/0B8O4jn0E_cvKNlM2R2J5UENKZEk/view?usp=sharing

**Comment by ixax** [comment]
Выложил

**Comment by drdim** [comment]
thks
