### ISSUE TITLE
Карточка. Выбор города

### ISSUE THREAD

**Issue by drdim** [ixax/fl-buket#21]
Сделать открывания окна выбора города доставки при нажатии на текущий город доставки.

**Comment by ixax** [comment]
Выпадашка такая же, как в фильтрах в каталоге?

**Comment by drdim** [comment]
На десктопе, наверное попап, а на мобилах можно через стандартный селектор.Он достаточно удобный на мобилках. Уточню как именно надо для попапа.

**Comment by ixax** [comment]
По результатам обсуждения появился https://github.com/ixax/fl-buket/issues/44.
Закрываю текущий
