### ISSUE TITLE
[Карточка товара] Выбор платежного шлюза

### ISSUE THREAD

**Issue by drdim** [ixax/fl-buket#22]
Я не знаю есть это в макетах или нет. Если нет - делаем по аналогии.http://jobs.silverplate.ru/megaflowers/?card#8
http://jobs.silverplate.ru/megaflowers/?card#9

**Comment by ixax** [comment]
В макетах этого нет

**Comment by drdim** [comment]
Могу дать макеты от меги, устроит? зеленого там вроде нет, поэтому подайдут.

**Comment by drdim** [comment]
Макетов нет, есть верстка готовая карточки товара, поможет?

**Comment by ixax** [comment]
Думаю да

**Comment by drdim** [comment]
отправил на почту.

**Comment by ixax** [comment]
Унес в фичи потому что попап появился в середине работ над проектом, но будет сделан сейчас.

**Comment by ixax** [comment]
Выложил
