### ISSUE TITLE
[android] Горизонтальная прокрутка

### ISSUE THREAD

**Issue by drdim** [ixax/fl-buket#26]
Имеется в portrait (копка меню наполовину обрезана). В landscape, меню по верх больше половины экрана, не видно букетов в таком виде.

**Comment by drdim** [comment]
https://drive.google.com/file/d/0B8O4jn0E_cvKVkJnMDlkR3U4LUk/edit?pli=1

**Comment by ixax** [comment]
Горизонтальную прокрутку зафиксил

**Comment by drdim** [comment]
https://drive.google.com/file/d/0B8O4jn0E_cvKaGhmdjg1TDV6VXc/edit?usp=docslist_api
