### ISSUE TITLE
Страница 404

### ISSUE THREAD

**Issue by ixax** [ixax/fl-buket#3]
http://ixax.github.io/fl-buket/404.html

**Comment by drdim** [comment]
Предлагаю для кнопок реализовать hover эффекты для декстопов.

**Comment by ixax** [comment]
Вынес в https://github.com/ixax/fl-buket/issues/4.
Нужно подумать над цветами. Можно опираться на цвета ссылок при наведении.

**Comment by ixax** [comment]
Тут всё
