### ISSUE TITLE
[Карточка товара] Нельзя изменить состав букета.

### ISSUE THREAD

**Issue by drdim** [ixax/fl-buket#30]
При нажатии на изменить букет, у количества появляется - и + который меняет количество цветка в букете. Пример. http://megaflowers.ru/bouquets/podnebese

**Comment by drdim** [comment]
https://drive.google.com/file/d/0B8O4jn0E_cvKYTZpUG9zZWlBaDA/view?usp=sharing
https://drive.google.com/file/d/0B8O4jn0E_cvKbi1lcFRKdVVQdDA/view?usp=sharing

**Comment by ixax** [comment]
Так же есть кнопка «Вернуть состав»

**Comment by drdim** [comment]
>Так же есть кнопка «Вернуть состав»

Да про нее забыли, на меге ссылкой, как делаем вернуть состав обсудили - все в одной кнопке.

**Comment by ixax** [comment]
Выложил
