### ISSUE TITLE
[Каталог] Фильтр вместе с выпадашкой «все размеры» выстроить в ряд

### ISSUE THREAD

**Issue by drdim** [ixax/fl-buket#32]
Чтобы оптимизировать пространство и так малого размера экрана, может стоит кнопу фильтра разместить вместе со всеми размерами? Будет 2 ряда вместо одного.

**Comment by ixax** [comment]
Думаю в тачах имеет смысл убирать текст «Фильтр»

**Comment by ixax** [comment]
Унес в большой ишью с правками в фильтрах https://github.com/ixax/fl-buket/issues/57
