### ISSUE TITLE
[Корзина] Баги списком.

### ISSUE THREAD

**Issue by drdim** [ixax/fl-buket#36]
- [x] Удалить товар из корзины нет экшена.
- [ ] Шрифт не в центре (вероятно сам по себе такой шрифт) везде отступы не корректны. Нужно это фиксить.
- [x] Даты выглядят совершенно странно (без отступов слева). 2 стрелки вниз. Стиль датапикера - не в тон сайта.
- [x] Без открытки - выпадающий список открыток, как на текущем работающем сайте.
- [x] Текстовое поле адреса вставляет обычный текст в 2 строки, половина адреса не видно. Либо тестовое поле делать больше, либо при вставке расширять, с автоподстановкой адреса такая же беда, видно только название города.https://drive.google.com/file/d/0B8O4jn0E_cvKX3lRX1dqLVB0SXc/edit?usp=drivesdk
- [x] Чекбокс, если описание в 2 строки, тоже выглядит ужасно: https://drive.google.com/file/d/0B8O4jn0E_cvKNEZjV1c1c3hsQnM/edit?usp=drivesdk
https://drive.google.com/file/d/0B8O4jn0E_cvKVk14eTRTXzdkcmc/edit?usp=drivesdk

https://drive.google.com/file/d/0B8O4jn0E_cvKYXlIdUp2WVFLbWc/edit?usp=drivesdk
https://drive.google.com/file/d/0B8O4jn0E_cvKRGtWNzNSeGFMTU0/edit?usp=drivesdk

**Comment by ixax** [comment]
Здесь все, проблемный шрифт вынес в https://github.com/ixax/fl-buket/issues/66
