### ISSUE TITLE
[шапка] При выделенном пунккте меню, иконка сливается с фоном

### ISSUE THREAD

**Issue by drdim** [ixax/fl-buket#63]
Думаю надо белым делать как корзину.
https://drive.google.com/file/d/0B8O4jn0E_cvKNVRvVmFXcURDM00/edit?usp=drivesdk

**Comment by ixax** [comment]
Да, этой иконки нет, сделаю на тебя issue

**Comment by drdim** [comment]
Ок

**Comment by ixax** [comment]
Иконки вынес в https://github.com/ixax/fl-buket/issues/77
