### ISSUE TITLE
[карточка товара] Смартфон

### ISSUE THREAD

**Issue by drdim** [ixax/fl-buket#64]
- [x] Сейчас после фото, идут видео и 360 просмотр + еще описание букета, приходится много листать чтобы добраться до кнопки купить. Предлагаю продублировать кнопку купить в адапте под мобильные - как в карточке товара, купить за 1000 р. Под фотографией букета. Чтобы инициировать быстрее покупку не вникая в размеры.
- [x] Не очень выглядит колонка с размерами купить и быстрая покупка. Я бы кнопки купить за  и быстрая покупка сделал крупнее. малый средний большой сделал в строку или вкладками. Чтобы меньше листать, сейчас 2 столбца сделали в один, и получилась много прокрутки, нужно скомпоновать и увеличить кнопки. (Возможно их сделать как двойная в фильтре в одну строку, как бы переключателем), аналогично со способом оплаты. Выглядит не закончено в текущем исполнении.
Пример макета, как хочется это увидеть https://moqups.com/drdim/roENp6XQ/p:aaf4eae6b

- [x]  Специальная гарантия и Акция сделать в одну строку, справа Акция, слева гарантия.

**Comment by ixax** [comment]
> Выглядит не закончено в текущем исполнении.
Что справедливо для отсутствия макетов :)

**Comment by ixax** [comment]
> Возможно их сделать как двойная в фильтре в одну строку, как бы переключателем

Вот вообще не понял

**Comment by drdim** [comment]
>Выглядит не закончено в текущем исполнении.
>Что справедливо для отсутствия макетов :)
Не спорю, сами кнопки можно увеличить изменить их местоположения, чтобы было меньше воздуха в этом  блоке.

**Comment by ixax** [comment]
Тут все
