### ISSUE TITLE
[корзина] android 

### ISSUE THREAD

**Issue by drdim** [ixax/fl-buket#67]
- [x] Верстка едет.
https://drive.google.com/file/d/0B8O4jn0E_cvKOW54bzhWMmJIWms/view?usp=sharing
- [x] Проблема с отступами, инпаты прижаты к правому экрану
- [x] Вход на сайт не оптимизирован под мобилки. https://drive.google.com/file/d/0B8O4jn0E_cvKSk5aU2JFSG5vMGs/view?usp=sharing
- [ ] Выделенное меню - выделять весь пункт меню, а не только надпись https://drive.google.com/file/d/0B8O4jn0E_cvKNHBsYUZ6MkdUTFk/view?usp=sharing

**Comment by ixax** [comment]
Четвертый пункт для меня загадка… Потому что я делал выделение всего пункта. Можешь сбросить кеши?
Кстати мобилку быстрее проверять в гуглохроме или Яндекс Браузере, в эмуляторе.

**Comment by ixax** [comment]
Третий пункт унёс в https://github.com/ixax/fl-buket/issues/48

**Comment by ixax** [comment]
Перепроверь четвертый пункт и если он и первые два ок — закрывай
