### ISSUE TITLE
[корзина] Десктоп

### ISSUE THREAD

**Issue by drdim** [ixax/fl-buket#68]
- [x] Вылезает окно авторизации на широких экранах. https://drive.google.com/file/d/0B8O4jn0E_cvKR2lpcDlOdEt0X1k/edit?usp=drivesdk
- [x] Текст скачет выше ( кнопка) ниже (напомнить) https://drive.google.com/file/d/0B8O4jn0E_cvKM0NaOWVJODltZzQ/edit?usp=drivesdk
- [x] Смещение на больших разрешения окна авторизации за пределы области сайта https://drive.google.com/file/d/0B8O4jn0E_cvKR2lpcDlOdEt0X1k/edit?usp=drivesdk
- [x] Выпадашка https://drive.google.com/file/d/0B8O4jn0E_cvKQTk5N01peGpORE0/edit?usp=drivesdk

**Comment by ixax** [comment]
@drdim Не понял третий пункт.
И четвертый - что не так с выпадашкой?

**Comment by ixax** [comment]
`Вылезает окно авторизации на широких экранах.` вынес восьмым пунктом в https://github.com/ixax/fl-buket/issues/48

**Comment by ixax** [comment]
@drdim До сих пор не понимаю смысла 3 и 4 пункта

**Comment by drdim** [comment]
>4 

Выпадашка смещена относительно правого края и отступ между нижним краем инпата и списком, по размерам - большие отступы.

>3 

Не то описание - на больших экранах - смещение за границы отрисовки экрана - аналогично с авторизацией на мобильных.

**Comment by ixax** [comment]
3-й пункт решен в https://github.com/ixax/fl-buket/issues/48

**Comment by ixax** [comment]
Здесь всё.
Если выпадашка будет вылезать вправо, то позиционируем её по правому краю кнопки.
Починил закрытие выпадашки при повторном нажатии на кнопку.
