### ISSUE TITLE
[каталог] Декстоп

### ISSUE THREAD

**Issue by drdim** [ixax/fl-buket#69]
- [ ] Фильтры https://drive.google.com/file/d/0B8O4jn0E_cvKTFQ5eHpBOE9uU2c/edit?usp=drivesdk
- [ ] Еще фильтры https://drive.google.com/file/d/0B8O4jn0E_cvKeV9MWHV4bEFyTU0/edit?usp=drivesdk

**Comment by ixax** [comment]
Оба бага правятся в https://github.com/ixax/fl-buket/issues/57 Закрываю как дубликат
