### ISSUE TITLE
Отрисовать иконки в векторе (svg на выходе)

### ISSUE THREAD

**Issue by ixax** [ixax/fl-buket#77]
- [ ] `Значки в хедере – корзина и консультант`. Должны становиться белыми при оранжевом фоне
- [ ] Попап продукта - `навигация влево вправо` + цвет при наведении
- [ ] `Крестик закрытия попапа` + он же при наведении
- [ ] `Значок телефонной трубки` в кнопке быстрой покупки в карточке товара (белый + оранжевый цвет)
- [ ] `Стрелка вниз на кнопках дропдаунов` (на странице каталога)
- [ ] `Крестик удаления фильтра` на странице каталога (справа в кнопке выбранного фильтра)
- [ ] `Сбросить` и `Вернуть` на странице каталога
- [ ] `Оранжевая галочка` в чекбоксе
- [ ] `Иконка календаря` в инпуте выбора даты на странице корзины
- [ ] `Иконка скачивания` на текстовой странице (см в макете)
- [ ] `Лупа`, появляющаяся при наведении на продукт в каталоге и главной странице (кстати это курсор? Тогда унжен `cur`-файл или просто иконка? (тогда просто svg)
- [ ] `Специальная гарантия` на странице товара
- [ ] `Акция - сэкономь 350 р.` на странице товара
- [ ] `Иконка на кнопке фильтры` на странице каталога
- [ ] `Звездочки отзывов` (пустая и заполненная звезда)
- [ ] `Иконка стрелки` вверх у ответов на отзывы
- [ ] favicon

**Comment by drdim** [comment]
Принял

**Comment by ixax** [comment]
Добавил `favicon`

**Comment by drdim** [comment]
https://drive.google.com/open?id=0B8O4jn0E_cvKOWIwc0syZHlsaWhKZ0tsRGduaHc5ckJlRzhF Иконки в svg.

**Comment by drdim** [comment]
Фавиайкон тоже будет (с нарезками в png), и еще рейтинга там не хватает.

**Comment by drdim** [comment]
Фавикон и недостающие в svg доложил в расшаренную папку
https://drive.google.com/drive/folders/0B8O4jn0E_cvKfi1McVFHa2xQaVNwTE1VbGhlTnYxbWhjaF9RdFNkeXhVSlUtRC1sLVVIbmc
