### ISSUE TITLE
Нет знака рубля на планшетах ipad в сафари

### ISSUE THREAD

**Issue by drdim** [ixax/fl-buket#8]
квадрат вместо символа

**Comment by ixax** [comment]
@drdim Тут какое дело: знак рубля сейчас вставляется utf-символом и смотрится достаточно гармонично, т.к. выполнен тем же шрифтом, что и у нас.
Есть другие методики, но знак рубля будет смотреться очень вычурно, т.к. будет написан другим щрифтом + много костылей.
Я предлагаю на девайсах без поддержки этого символа писать просто `р.`, как на megaflowers сейчас. Меньше костылей и меньше вероятность какому-то пользователю показать неверно отрисованный, а то и просто сломанный значек.

**Comment by drdim** [comment]
ок. Давай делать так.
