### ISSUE TITLE
[Текстовая страница] Выравнивание текста, ширина блока (планшет)

### ISSUE THREAD

**Issue by linius** [ixax/fl-buket#85]
![img_2355](https://cloud.githubusercontent.com/assets/892514/8717237/e2b36742-2bb2-11e5-914d-d2f64b8f9564.PNG)
Стоит выровнять текст по ширине и убрать правое пустое поле.

**Comment by ixax** [comment]
Ок, но сделано четко по макету

**Comment by ixax** [comment]
Тут все
