### ISSUE TITLE
Каталог. Оличается фильтр

### ISSUE THREAD

**Issue by drdim** [ixax/fl-buket#95]
https://drive.google.com/file/d/0B8O4jn0E_cvKMHIxTG4tQU0td3M/view?usp=drivesdk
http://jobs.silverplate.ru/buket74/i/1982069626543511040-2-%D0%BA%D0%B0%D1%82%D0%B0%D0%BB%D0%BE%D0%B3-%D0%BA%20%D1%81%D0%BE%D0%B1%D1%8B%D1%82%D0%B8%D1%8E.png

**Comment by ixax** [comment]
Я не вижу отличия :)
